
language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: d5298676-c3cb-4ede-aa2f-a73ed960e89c
  app: project-103-jawgz
  on:
    repo: uva-cs3240-f19/project-103-jawgz