
language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: K3zXMSRVaYac9XyG5NxZu3mKgNXLRRxUJ6n1F8dEzJTmYQ1/lsiUVgM9ERZuvwTdB9YsoajzJa07NF8Z/r3jXJcDURbhKZE68v+ElTXeSZBAGuvC3lrxjEQvqdrpkMdxUvXd5+A81Btjrpf8PZyBlvnl+ToE2+0YOiYEF5Tzmesw1gsBtCQ3QTrrQzD65HBtQZK4PbYcLxdjzfwC+Yskrnm8x5Pn9n+jqgIPfkv5DnlgiG4T8RBtzF8H1mRNNGJcjpPCDHkryjDHVXiA5VegBu6nP42U2NLB9JscswRDKxvjM3+0pX0PN+NZ/KxEFRO9O93ayFbS3dPAHJK8B+O9uGZKwDf6S4icCM7OkBVtIi6HMHQbCsZcbzW06pkNqzTeTo+sq29ORtVUNAaF01TP3NuMEqZRtGrMQOUbEECpiMCMnAOqCZOYkCwoUet8BZKpwiO0ZnRD5+oRT+jNHIj888UDa4f2FrSSG6eZb2cQYCES2wMli1KaYz4GVURVklL/QZFzXIIv+2yFXqMpvObJN1nlgxlLEqmQUOYWqxQyGN8rs79PBkANxOb1fgWoy/v7JcqYyD0aE61XNBPiOujkXvK1MyUY5K7BSES+eSUE01Pm8BL7P8+8Xqo1noHzqJVIkwzil+i4UYjacVgs0M+1e+GE9Yqab4ur66HExSMlAX4=
  app: project-103-jawgz
  on:
    repo: uva-cs3240-f19/project-103-jawgz