# Generated by Django 2.2.5 on 2019-10-19 01:22

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='riding_date',
            field=models.DateTimeField(default=post.models.default_datetime),
        ),
    ]
