# Generated by Django 2.2.5 on 2019-10-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_posting_riding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='driver_id',
            field=models.IntegerField(default='00000', max_length=200),
        ),
    ]
