# Generated by Django 2.2.5 on 2019-10-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_posting_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='driver_id',
            field=models.CharField(default='00000', max_length=200),
        ),
    ]
