# Generated by Django 2.2.5 on 2019-10-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191019_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='driver_id',
        ),
    ]
