# Generated by Django 2.2.5 on 2019-10-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20191019_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='driver_id',
            field=models.CharField(max_length=200),
        ),
    ]
