# Generated by Django 2.2.5 on 2019-10-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20191019_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='num_passengers',
            field=models.IntegerField(default=0),
        ),
    ]
