# Generated by Django 2.2.5 on 2019-10-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
