# Generated by Django 2.2.5 on 2019-10-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postings',
            field=models.TextField(blank=True),
        ),
    ]
