# Generated by Django 2.2.5 on 2019-11-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
