# Generated by Django 2.2.5 on 2019-11-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20191112_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='name',
            field=models.CharField(default='No Name', max_length=200),
        ),
    ]
