# Generated by Django 2.2.5 on 2019-11-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_rider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='rider',
            name='ratings_list',
            field=models.TextField(default=','),
        ),
    ]
