# Generated by Django 2.2.5 on 2019-11-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rider_image 2'),
        ('user_profile', '0004_rider_name'),
        ('user_profile', '0003_auto_20191112_1921 2'),
        ('user_profile', '0004_rider_name 2'),
    ]

    operations = [
    ]
