# Generated by Django 2.2.5 on 2019-11-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_merge_20191113_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
