# Generated by Django 2.2.5 on 2019-11-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20191114_1910'),
        ('user_profile', '0005_auto_20191117_1903'),
    ]

    operations = [
    ]
