# Generated by Django 2.2.5 on 2019-11-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20191117_1903'),
        ('user_profile', '0005_auto_20191117_1903 2'),
        ('user_profile', '0002_rider_image 3'),
        ('user_profile', '0006_auto_20191114_1910'),
        ('user_profile', '0004_rider_name 3'),
        ('user_profile', '0003_auto_20191112_1921 3'),
    ]

    operations = [
    ]
