# Generated by Django 2.2.5 on 2019-11-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_merge_20191117_2223'),
        ('user_profile', '0007_merge_20191117_2050'),
    ]

    operations = [
    ]
