# Generated by Django 2.2.5 on 2019-11-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_merge_20191118_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
