# Generated by Django 2.2.5 on 2019-12-01 22:10

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20191118_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='cellphone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
