# Generated by Django 2.2.5 on 2019-12-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20191201_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='cellphone',
            field=models.IntegerField(),
        ),
    ]
