# Generated by Django 2.2.5 on 2019-12-01 23:04

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20191201_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='cellphone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
