# Generated by Django 2.2.5 on 2019-10-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='riding_date',
        ),
    ]
