# Generated by Django 2.2.5 on 2019-10-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='driver_id',
            field=models.CharField(default='0000000', max_length=200),
        ),
        migrations.AddField(
            model_name='posting',
            name='uid',
            field=models.CharField(default='0000000', max_length=200),
        ),
    ]
