# Generated by Django 2.2.5 on 2019-11-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
