# Generated by Django 2.2.5 on 2019-10-22 02:34

from django.db import migrations, models
import find.models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='riding_date',
            field=models.DateTimeField(default=find.models.default_datetime),
        ),
    ]
