# Generated by Django 2.2.5 on 2019-11-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_posting_riding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='posting_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posting',
            name='riders_requested',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posting',
            name='riders_riding',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
