# Generated by Django 2.2.5 on 2019-11-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_posting_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='ratable_by',
            field=models.TextField(default=','),
        ),
    ]
