# Generated by Django 2.2.5 on 2019-10-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_auto_20191014_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='driver_id',
            field=models.IntegerField(default='00000', max_length=200),
        ),
        migrations.AddField(
            model_name='posting',
            name='uid',
            field=models.IntegerField(default='00000', max_length=200),
        ),
    ]
