# Generated by Django 2.2.5 on 2019-10-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_auto_20191013_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='price',
            field=models.CharField(default=5.0, max_length=200),
            preserve_default=False,
        ),
    ]
