# Generated by Django 2.2.5 on 2019-10-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0003_auto_20191019_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='uid',
        ),
    ]
