# Generated by Django 2.2.5 on 2019-11-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0003_posting_ratable_by 2'),
        ('find', '0003_posting_ratable_by'),
    ]

    operations = [
    ]
