# Generated by Django 2.2.5 on 2019-11-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0004_remove_posting_posting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='posting_id',
            field=models.CharField(default=-8275416270096498273, max_length=200),
        ),
    ]
