# Generated by Django 2.2.5 on 2019-10-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0004_remove_posting_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='driver_id',
            field=models.CharField(default='00000', max_length=200),
        ),
    ]
